apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm-listener
  labels:
    app: npm-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npm-listener
  template:
    metadata:
      labels:
        app: npm-listener
    spec:
      containers:
      - name: npm-listener
        image: gcr.io/updateyapp/npmlistener:latest
        imagePullPolicy: Always
