apiVersion: apps/v1
kind: Deployment
metadata:
  name: npm-listener
  labels:
    app: npm-listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: npm-listener
  template:
    metadata:
      labels:
        app: npm-listener
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: npm-listener
      containers:
      - name: npm-listener
        image: gcr.io/updateyapp/npmlistener:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
